$kind: http-request
description: Retrieve a view configuration for an entity. An admin user can only
  retrieve their own configurations.
url: "{{baseUrl}}/admin/views/:entity/configurations/:id?fields=string"
method: GET
headers:
  Accept: application/json
queryParams:
  - key: fields
    value: string
    description: Comma-separated fields that should be included in the returned
      data. If a field is prefixed with `+` it will be added to the default
      fields, using `-` will remove it from the default fields. Without prefix
      it will replace the entire default fields.
pathVariables:
  - key: entity
    value: string
    description: The entity to retrieve its view configurations (for example, `orders`)
  - key: id
    value: string
    description: The ID of the view configuration to retrieve.
auth:
  type: bearer
  credentials:
    token: "{{bearerToken}}"
examples: ./.resources/Get View Configuration.resources/examples
order: 1000
