$kind: http-request
description: Update the view configuration of an entity. An admin user can only
  update their own configurations.
url: "{{baseUrl}}/admin/views/:entity/configurations/:id"
method: POST
headers:
  Content-Type: application/json
  Accept: application/json
pathVariables:
  - key: entity
    value: string
    description: The entity to update its view configuration (for example, `orders`).
  - key: id
    value: string
    description: The view configuration's ID.
body:
  type: json
  content: |-
    {
      "set_active": true,
      "name": "string",
      "is_system_default": true,
      "configuration": {
        "search": "string",
        "visible_columns": [
          "string",
          "string"
        ],
        "column_order": [
          "string",
          "string"
        ],
        "column_widths": {},
        "filters": {},
        "sorting": {
          "id": "string",
          "desc": true
        }
      }
    }
auth:
  type: bearer
  credentials:
    token: "{{bearerToken}}"
examples: ./.resources/Update View Configuration.resources/examples
order: 2000
