export const CART_ERRORS = {
  "CART.NOT_FOUND": 404,
  "CART.ITEM_NOT_FOUND": 404,
  "CART.VARIANT_NOT_UNSELECTED": 400,
  "CART.UNSELECTED_QUANTITY_EXCEEDED": 400,
  "CART.INVALID_QUANTITY": 400,
  "CART.USE_VARIANT_QUANTITY_ENDPOINT": 400,
} as const;
